# Generated by Django 6.0.2 on 2026-05-13 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('specializace', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lekce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('datum_cas', models.DateTimeField()),
                ('kapacita', models.PositiveIntegerField()),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervace.kategorie')),
                ('trener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervace.trener')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('lekce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervace.lekce')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervace.zakaznik')),
            ],
        ),
    ]
