# Generated by Django 6.0.2 on 2026-06-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategorie',
            table='rezervace_kategorie',
        ),
        migrations.AlterModelTable(
            name='lekce',
            table='rezervace_lekce',
        ),
        migrations.AlterModelTable(
            name='rezervace',
            table='rezervace_rezervace',
        ),
        migrations.AlterModelTable(
            name='trener',
            table='rezervace_trener',
        ),
        migrations.AlterModelTable(
            name='zakaznik',
            table='rezervace_zakaznik',
        ),
    ]
